FROM mcr.microsoft.com/playwright:v1.58.2-noble

WORKDIR /workspace

RUN corepack enable && corepack prepare yarn@4.12.0 --activate || true

COPY .yarn/releases/ ./.yarn/releases/
COPY package.json yarn.lock .yarnrc.yml .yarn/releases/** playwright.config.ts ./
RUN yarn install

CMD ["yarn", "playwright", "test"]
